language: r

cache:
  packages: yes

script:
  - Rscript -e 'install.packages("rmarkdown")'
  - Rscript -e 'install.packages("knitr")'
  - Rscript -e 'install.packages("kableExtra")'
  - Rscript -e 'source("Process.R")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_CI
  keep_history: true
  on:
    branch: master
