language: r

r_packages:
  - rmarkdown
  - knitr
  - kableExtra

cache:
  packages: yes

branches:
  only:
    - master

script:
  - Rscript -e 'source("Process.R")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_CI
  keep_history: true
  local_dir: docs
  on:
    branch: master
